version: "3.8"

services:
  icargo:
    build: .
    container_name: icargo
    restart: always
    volumes:
      - icargo_sqlite_data:/data  # Храним базу данных в Volume
    env_file:
      - .env  # Загружаем переменные окружения из файла
    ports:
      - "3303:3303" # Проброс порта наружу
    user: "1000:1000"  # Запускаем контейнер от UID/GID 1000 (обычный пользователь в Linux)

volumes:
  icargo_sqlite_data:
