version: "3.8"

services:
  icargo:
    build: .
    container_name: icargo
    restart: always
    volumes:
      - sqlite_data:/data  # Храним базу данных в Volume
    env_file:
      - .env  # Загружаем переменные окружения из файла
    user: "1000:1000"  # Запускаем контейнер от UID/GID 1000 (обычный пользователь в Linux)

volumes:
  sqlite_data:
